### ISSUE TITLE
 brew install homebrew/gui/meld => ImportError: No module named cairo

### ISSUE THREAD

**Issue by harobed** [Homebrew/homebrew-gui#38]
When I install Meld with:

```
$ brew install homebrew/gui/meld
```

I've this error:

```
meld
Couldn't bind the translation domain. Some translations won't work.
'module' object has no attribute 'bindtextdomain'
2016-10-24 10:26:24.988 Python[2926:49056752] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
Traceback (most recent call last):
  File "/usr/local/bin/meld", line 286, in <module>
    import meld.meldapp
  File "/usr/local/lib/python2.7/site-packages/meld/meldapp.py", line 31, in <module>
    import meld.ui.util
  File "/usr/local/lib/python2.7/site-packages/meld/ui/util.py", line 23, in <module>
    from meld.ui import gladesupport
  File "/usr/local/lib/python2.7/site-packages/meld/ui/gladesupport.py", line 3, in <module>
    from meld import diffmap
  File "/usr/local/lib/python2.7/site-packages/meld/diffmap.py", line 19, in <module>
    import cairo
ImportError: No module named cairo
```

Best regards,
Stéphane

**Comment by harobed** [comment]
This is the fix:
This is my fix:

```
$ brew remove python
$ brew remove meld
$ brew remove cairo
$ brew uninstall --force py2cairo
$ brew uninstall --force pygtk
$ brew remove python pygtk
$ brew install homebrew/gui/meld
```

It's possible to fix this bug directly in howebrew system with do this hack?

**Comment by MikeMcQuaid** [comment]
This has been moved to Homebrew Cask.
