### ISSUE TITLE
Hexchat brew install errors with OS X Sierra (10.12)

### ISSUE THREAD

**Issue by ctcyang** [Homebrew/homebrew-gui#40]
brew install homebrew/gui/hexchat --with-python
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Installing hexchat from homebrew/gui
==> Installing dependencies for homebrew/gui/hexchat: xz, intltool, gdk-p
==> Installing homebrew/gui/hexchat dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/xz-5.2.2.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/xz/5.2.2
Last 15 lines from /Users/carlyang/Library/Logs/Homebrew/xz/01.configure:
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether ln -s works... yes
checking for style of include used by make... GNU
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/xz20161102-2202-9yobon/xz-5.2.2':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

READ THIS: https://git.io/brew-troubleshooting

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:523:in `open'
	from /usr/local/Library/Homebrew/utils.rb:553:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:585:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:222:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:218:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:263:in `dump'
	from /usr/local/Library/brew.rb:186:in `rescue in <main>'
	from /usr/local/Library/brew.rb:76:in `<main>'

**Comment by ctcyang** [comment]
Never mind. Should've read documentation more carefully:

brew update
brew install homebrew/gui/hexchat --with-python

reveals that:
Error: Your Xcode (7.2) is outdated.
Please update to Xcode 8.1 (or delete it).
Xcode can be updated from the App Store.
